### ISSUE TITLE
Streams don't load

### ISSUE THREAD

**Issue by fubarduck** [marshallthornton/Twitch.tv-Plex-Plugin#1]
When I try loading any stream, it stays on the loading screen with the cancel button indefinitely. Seems to not work at all anymore.

**Comment by jgrowl** [comment]
Doesn't work for me either.

**Comment by problemss** [comment]
same here

**Comment by AndreasKarlsen** [comment]
Same problem here.
Please tell me how to assist you in fixing it, by assisting with logs or what ever you need.

**Comment by furier** [comment]
Same here ending up getting "no data available" do i need to open a port or something?

**Comment by marshallthornton** [comment]
Can you verify that the latest version of flash player is installed on the system running the media server? I think the plugin requires that in order to transcode the live stream.

**Comment by furier** [comment]
I will try and do that, will get back to you.
Den 21. juni 2013 07:29 skrev "Marshall Thornton" notifications@github.com
følgende:

**Comment by furier** [comment]
so did I, Tho Im running the server on an ubuntu server, installed some
flash plugin stuff, but didnt help, maybe ubuntu is not supported?

2013/6/28 m1r0 notifications@github.com

**Comment by marshallthornton** [comment]
Possibly, I have only tested and run it on a Windows machine, I may have a new version to try out in the next couple weeks depending on how much spare time I can put into it after work.

**Comment by enyo** [comment]
The plugin did not work at all for me (just a grey screen) until I installed the latest Flash plugins for Mac OS thanks to this comment by @pejoo 

> Can you verify that the latest version of flash player is installed on the system running the media server? I think the plugin requires that in order to transcode the live stream.

**EDIT**: Thanks BTW @pejoo. It's working great for me now, and I'm able to watch the StarCraft II WCS without any problems :+1:

**Comment by Crashme** [comment]
Could you create a Plugin which works for Azubu TV too? :-)

**Comment by marshallthornton** [comment]
Gonna close this as original issue was due to Flash and now that should no longer be a requirement either so shouldn't run into the loading issue anymore.
