### ISSUE TITLE
Plugin stopped working: failed to open source

### ISSUE THREAD

**Issue by pencil** [marshallthornton/Twitch.tv-Plex-Plugin#7]
The plugin used to work for me, but now I'm unable to watch any stream. Browsing the list of available streams still works. When I try to access a stream however, I get a "Please wait" which disappears shortly after. In the log file I see:

```
18:04:09 T:4391452672  NOTICE: Thread MediaDecision start, auto delete: false
18:04:11 T:140735150666512  NOTICE: DVDPlayer: Opening: http://usher.justin.tv/stream/multi_playlist/northcontv.m3u8?token=0cac1cf1ba86515df500ffe23dcab6397cc9bcad%3Ab0bd69e4450cbf8e961f4546ffabb4575cd5a8df%3A%7B%22expiration%22%3A%201386349749.5256071%2C%20%22channel%22%3A%20%22northcontv%22%2C%20%22user_agent%22%3A%20%22.%2A%22%7D&hd=true
18:04:11 T:140735150666512 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:04:11 T:4391452672  NOTICE: Thread CDVDPlayer start, auto delete: false
18:04:11 T:4391452672  NOTICE: Creating InputStream
18:04:12 T:4391452672   ERROR: Open - failed to open source <http://usher.justin.tv/stream/multi_playlist/northcontv.m3u8?token=0cac1cf1ba86515df500ffe23dcab6397cc9bcad%3Ab0bd69e4450cbf8e961f4546ffabb4575cd5a8df%3A%7B%22expiration%22%3A%201386349749.5256071%2C%20%22channel%22%3A%20%22northcontv%22%2C%20%22user_agent%22%3A%20%22.%2A%22%7D&hd=true>
18:04:12 T:4391452672  NOTICE: Creating Demuxer
```

**Comment by pencil** [comment]
Seems to be an issue with Plex' Justin.tv helper. Managed to workaround it, but maybe you guys know a better solution: https://forums.plexapp.com/index.php/topic/88770-complexapppluginsjustintv-stopped-working-with-twitchtv-urls

**Comment by pencil** [comment]
Extracted my URL service into a plugin: https://github.com/pencil/Fix-Twitch.tv-Plex-Plugin
My first idea was to open up a pull request, to have the fix in this plugin. But it didn't work, because the plugin containing the buggy twitch.tv handling is loaded before the this plugin :unamused:

**Comment by marshallthornton** [comment]
I added a note to the readme about the error and your plugin so hopefully anyone else encountering the error will see it.

Once Plex updates the main Services.bundle to fix the twitch.tv URL handling I can remove it from the readme

**Comment by pencil** [comment]
Should be fixed in the next Plex Media Server release: https://github.com/plexinc-plugins/Services.bundle/pull/663

**Comment by marshallthornton** [comment]
Closing as it looks like the latest version of Plex has the changes referenced above in it now. If you still have this error please make sure your Plex Media Server is up to date.
