### ISSUE TITLE
"File not found"

### ISSUE THREAD

**Issue by ghost** [marshallthornton/Twitch.tv-Plex-Plugin#8]
Hi,

Just came across this plugin and managed to install it without any problems.
But when I try to open a stream it loads for a couple of seconds and then I receive an error: "File not found!" on all streams.

Also when I try to open the "Followed" list it says "No data available" all the time. (I entered my username in the Plexweb).

Any ideas?
Running Plex Media Server 0.9.8.13 on a Samsung SmartTV UE5F8005.

**Comment by andreasschmitz** [comment]
The solution described in Issue  https://github.com/pejoo/Twitch.tv-Plex-Plugin/issues/7 fixed the problem in my case :)

**Comment by marshallthornton** [comment]
Ok, good to hear, I updated the readme to help point anyone else having this issue in the right direction
